#%RAML 1.0 DataType
type: object
properties:
  status:
    type: string
  apiName:
    type: string
  version:
    type: string
  timestamp:
    type: datetime
  uptime:
    type: integer
  salesforceConnectivityStatus:
    type: string
